### ISSUE TITLE
"PRINT_BASE_URL" and "proxyBaseUrl" undocumented 

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/mapfish-print#31]
MapFish print plugin reportedly requires  PRINT_BASE_URL system property and proxyBaseUrl setting in the plugin configuration  to function properly behind a proxy but this is undocumented in the wiki.

Examples:
At the top of <GEOSERVER_DATA_DIR>/printing/config.yaml:
`proxyBaseUrl: https://my.domain.com/geoserver/pdf`

JAVA_OPTS:
`-DPRINT_BASE_URL=https://my.domain.com/geoserver/`

**Comment by tdipisa** [comment]
Documented [here]([url](https://mapstore.readthedocs.io/en/latest/developer-guide/printing-module/))
