### ISSUE TITLE
Port mapfish-print latest master improvements to the GeoNode branches

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/mapfish-print#47]
Currently MapStore and GeoNode use two different versions of the mapfish-print library.
We need to:
 - port the latest improvements done for the GEOINFO work to the GeoNode specific branches (for GeoNode versions 3.3.x and master)
   -  https://github.com/geosolutions-it/mapfish-print/commit/97fd638282ba5ec3aa02e90ab8a08d6ddbf250fa
   - https://github.com/geosolutions-it/mapfish-print/commit/97401442557877e5fa2960a709b54e8058e0db93
 - try to harmonize the two so that we can converge on a single version for both MapStore and GeoNode

We are going to test the ported commits on the latest GeoServer 2.19.x as a proof of compatibility with GeoNode.

**Comment by mbarto** [comment]
@afabiani @simboss I have opened a draft PR here (https://github.com/geosolutions-it/mapfish-print/pull/49) with the results of my investigation on harmonizing the MapStore and GeoNode/GeoServer versions of print-lib.

The PR includes the most impactful upgrades of the GeoNode version into the master branch (used by MapStore).
Merging the PR should allow the same version to work fine in GeoServer/GeoNode and MapStore.

There are some additional improvements done by @afabiani that I have not included yet in this PR, because I need to have a deeper look on them to understand if they can conflict in some way with MapStore. Additional info is in the PR. 

Please let me know how to (eventually) proceed.

**Comment by afabiani** [comment]
Done
